spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://baseball-instance.cp4ew0qu6gis.ap-northeast-2.rds.amazonaws.com:5432/baseball
    username: lions
  https://devyurim.github.io/python/crawler/2018/08/11/crawler-1.html   password: 2wogus&rladuddnd

# 스크래핑을 위한 web-driver 위치 설정
path:
  web-driver: /opt/chromedriver