spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://baseball-instance.cp4ew0qu6gis.ap-northeast-2.rds.amazonaws.com:5432/baseball
    username: lions
    password: 2wogus&rladuddnd