server:
  port: 8090

spring:
  application:
    name: kbo-batch
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  batch:
    job:
      enabled: true
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: always

scrap:
  ranking: https://www.koreabaseball.com/Record/TeamRank/TeamRankDaily.aspx
  game: https://m.sports.naver.com/kbaseball/schedule/index?category=kbo&date=${today}
  score: https://m.sports.naver.com/kbaseball/schedule/index?date=${today}